version: '3.9'

services: 
  angular:
    container_name: hyacinthFE
    build: 
      context: ./hyacinthFE
      dockerfile: Dockerfile
    ports: 
      - 4200:4200
    volumes: 
      - ./hyacinthFE:/workspace/angular
      - /workspace/angular/node_modules
  
  fastapi:
    build: 
      context: ./hyacinthBE
    container_name: hyacinthBE
    volumes:
      - ./hyacinthBE:/workspace/fastapi
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    container_name: hyacinthDB
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPY_PASSOWRD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./sql_scripts:/workspace/scripts
      - hyacinth_db:/var/lib/mysql

volumes: 
  hyacinth_db: